In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'E:\\Apps\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
arr=np.array([1,2,3,4,"Drahsty",6])
print(arr,'\n',arr[2])

['1' '2' '3' '4' 'Drahsty' '6'] 
 3


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [18]:
np.linspace(0,1,11) #creates array of 11 elements woth numbers between 0 and 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-Dimentional Array

In [20]:
np.zeros((5,2)) # 5 rows 2 cols with 0 values

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print(arr[0][1])
print(arr[0,1])

2
2


In [26]:
arr[0][1]=20

In [27]:
arr

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
arr[2]=[1,2,1]

In [30]:
arr

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  2,  1]])

In [32]:
arr[:,1] # all rows and col=1

array([20,  5,  2])

In [34]:
arr[1,:] # all cols of row=1

array([4, 5, 6])

In [35]:
arr[1,:] = [0,0,0]

In [36]:
arr

array([[ 1, 20,  3],
       [ 0,  0,  0],
       [ 1,  2,  1]])

## Randomly Generated Arrays

In [41]:
np.random.seed(2) # keeps the random numbers of array as it is every time its generated
np.random.rand(5,2) # 5 ros 2 col with random values

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [42]:
np.random.seed(2) # keeps the random numbers of array as it is every time its generated
np.random.randn(5,2) # 5 ros 2 col with random values

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [44]:
np.random.seed(2) # keeps the random numbers of array as it is every time its generated
100* np.random.rand(5,2) # 5 ros 2 col with random values btwn 0,100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [47]:
np.random.seed(2) # keeps the random numbers of array as it is every time its generated
np.random.randint(low=0,high=100,size=(5,2)) # 5 ros 2 col with random values btwn 0,100

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise Operation

In [48]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [55]:
b=(10+(a*2)) ** 2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [56]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison Operation

In [58]:
a+b>=2

array([False,  True,  True,  True,  True])

In [59]:
a>b

array([False, False,  True,  True,  True])

In [63]:
a[a>b] # instead of booleans values it returns elements of array "a"

array([2, 3, 4])

In [64]:
b[a>b] # instead of booleans values it returns elements of array "b"

array([1.96, 2.56, 3.24])

## Summarizing Operations

In [71]:
a

array([0, 1, 2, 3, 4])

In [65]:
a.min() # returns min no

0

In [67]:
a.max() # returns max no 

4

In [68]:
a.sum()

10

In [69]:
a.mean()

2.0

In [70]:
a.std()

1.4142135623730951

## Vector-Vector Multiplication (Dot Product)

In [76]:
u=np.array([2,4,5,6])
v=np.array([1,0,0,2])
def v_v_mul(u,v):
    assert u.shape[0]==v.shape[0] # check the shape is equal
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result=result+u[i]*v[i]
    return result
v_v_mul(u,v)

14.0

In [77]:
u.dot(v) # dot operation

14

## Matrix-Vector Multiplication

In [86]:
U=np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
v=np.array([1,0,0,2])
def matrix_vector_mul(U,v):
    assert U.shape[1]==v.shape[0] # no of u.shape columns=4 i== no. of elements in v=4
    n=U.shape[0] # has 3 rows in u.shape=3
    result=np.zeros(n)
    for i in range(n):
        result[i]=v_v_mul(U[i],v)
    return result
matrix_vector_mul(U,v)

array([14.,  5.,  5.])

In [87]:
U.dot(v)

array([14,  5,  5])

## Matrix-Matrix Multiplication

In [103]:
U=np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
V=np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])
def matrix_matrix_mul(U,V):
    assert U.shape[1]==V.shape[0] # no of u.shape columns=4 i== no. of elements in v=4
    nrows=U.shape[0] # has 3 rows in U.shape=3
    ncols=V.shape[1] # has 3 cols in V.shape=3
    result=np.zeros((nrows,ncols))
    for i in range(ncols):
        Vi=V[:,i]
        UVi=matrix_vector_mul(U,Vi)
        result[:,i]=UVi
    return result
matrix_matrix_mul(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [104]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [105]:
 I=np.eye(3)

In [106]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [109]:
Vsq=V[[0,1,2]] # Take first 3 rows of V matrix
Vsq

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [110]:
Vsq_inverse=np.linalg.inv(Vsq) # Vsq-> Vsq inverse
Vsq_inverse

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [111]:
# Formula - V.V_inverse = I(Identity Matrix)
Vsq_inverse.dot(Vsq)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])